### ISSUE TITLE
Add an option to fill some buffer beforing sending to chromecast

### ISSUE THREAD

**Issue by jsalatiel** [Pat-Carter/stream2chromecast#18]
Could you add some buffer option to the source video before sending to chromecast ? Over 802.11b cache a few seconds  before start streaming would avoid pauses during play.
I dont know exactly how you could do it since you are streaming from a stdin pipe, but i think there is some way to increase the stdin buffer,

**Comment by Pat-Carter** [comment]
That's an interesting thought. I'll have a look into how we could go about that.

I guess we're talking about specifically when transcoding as that's where the transcoder command returns its output though stdout from the transcoder process to the HTTP server which sends it to the Chromecast.

The default settings for the transcoder mean that it will run fast but produce more data. Because it is transcoding in real-time, we use the "ultrafast" preset which produces a larger file but very quickly. 

Also, the default video bitrate is 2000k, which is quite high quality but again requires more data.

So, I guess there might be 2 different things that would cause pauses.

1. The network connection isn't fast enough to get all the data across to the device.
2. The computer isn't fast enough to transcode the file in real time.

If there are pauses due to network speed limitations, you might be able to improve this by adding transcode options to override the video bitrate.

e.g. :-

stream2chromecast.py -transcodeopts '-b:v 1000k -b:a 128k' -transcode <file>

...that should make the file smaller.

If the pauses are due to the computer not being fast enough, then, as you say, I guess some kind of buffering is the only solution. 

I'll give it some thought.

cheers,

Pat

**Comment by jsalatiel** [comment]
Hi Paul, i did a few tests over this couple of days i found out that using 
ffmpeg_process = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE, shell=True, bufsize=5242880) appears to give me some seconds of buffer which helps A LOT over the low bandwidth of 802.11b ! 5242880 was a wild guess =)

**Comment by Pat-Carter** [comment]
Fantastic - thanks!

That looks like job done then. I'll get that added as soon as I can.

Pat 

:-)

**Comment by jsalatiel** [comment]
=)

**Comment by Pat-Carter** [comment]
-transcodebufsize parameter added
