### ISSUE TITLE
Specify or change playback location

### ISSUE THREAD

**Issue by dieuwedeboer** [Pat-Carter/stream2chromecast#27]
Thank you for this script, it's been a great find and I've enjoyed using it over the past few days.

The main sorely lacking feature I've come across is the need to specify (or change) the playback location.

For example if playing a feature length movie file, I cannot find a way to stop half way and then come back to that spot later.

It would be useful to either have a flag that would set the starting playback location on a file and/or to have a flag that can change the playback location on a running file.

(I checked pychromecast and apparently they do have this feature, but I haven't had the time to look for the specific implementation.)

**Comment by appelflap** [comment]
Was searching for this as well because I tried to resume playback. Found that @dominicletz added a seek parameter to the script in db3440ead952d9fbad9f8ceb354b624af4bd934e. But it is incompatible with the current model load function in master because of additions for the subs.

**Comment by dieuwedeboer** [comment]
Since pychromecast was removed as a dependency that commit isn't really that usefull to us I think, here is a link to the current implementation there: https://github.com/balloob/pychromecast/blob/master/pychromecast/controllers/media.py#L361

Tried to convert it for use as a "while running" command here, but no luck so far:

```
diff --git a/cc_media_controller.py b/cc_media_controller.py
index c70982f..e7c29f4 100644
--- a/cc_media_controller.py
+++ b/cc_media_controller.py
@@ -428,6 +428,20 @@ class CCMediaController():
 
 
 
+    def seek(self, position):
+        """ Seek the media to a specific location. """
+
+        self.connect("receiver-0")
+
+        data = {"type":"SEEK", "currentTime":position, "resumeState":"PLAYBACK_START"}
+        namespace = "urn:x-cast:com.google.cast.receiver"
+        response = self.send_msg_with_response(namespace, data)
+        print(response)
+
+        self.close_socket()
+
+
+
     def set_volume(self, level):
         """ set the receiver volume - a float value in level for absolute level or "+" / "-" indicates up or down"""
 
diff --git a/stream2chromecast.py b/stream2chromecast.py
index 280a5d8..421f4a2 100755
--- a/stream2chromecast.py
+++ b/stream2chromecast.py
@@ -575,6 +575,11 @@ def stop(device_name=None):
     CCMediaController(device_name=device_name).stop()
 
 
+def seek(p, device_name=None):
+    """ seek playback """
+    CCMediaController(device_name=device_name).seek(p)
+
+
 def get_status(device_name=None):
     """ print the status of the chromecast device """
     print CCMediaController(device_name=device_name).get_status()
@@ -696,6 +701,9 @@ def run():
     elif args[0] == "-continue":
         unpause(device_name=device_name)
 
+    elif args[0] == "-seek":
+        seek(args[1], device_name=device_name)
+
     elif args[0] == "-status":
         get_status(device_name=device_name)
 
```

Returns:

`{u'reason': u'INVALID_COMMAND', u'type': u'INVALID_REQUEST', u'requestId': 2}`

Which seems to be about as helpful as an "it doesn't work" message would be. I could be missing an obvious chunk of the implementation. I don't know. Any help would be appreciated.

**Comment by Pat-Carter** [comment]
The way Stream2chromecast works is to send a command to the Chromecast instructing the media-player app to play a file found at a URL. The URL it supplies points back to the PC sending the command.

The script then sets up a single-request HTTP server to send the file to the Chromecast when it requests it.

The HTTP server doesn't know anything about the file except its mime-type.

In order to seek to a position, the HTTP server would have to be able to be able to work out where in the file to start serving from. e.g. which byte position represents x minutes into the media. 

Obviousy, the number of bytes that represents a minute of media varies considerably within the file.

So from that perspective, it would appear to be impossible to be able to seek to a position (at least in Stream2Chromecast).

I believe it is possible to do this using the transcoder though, by passing ffmpeg parameters in with -transcodeopts.

For example, to seek to 15 minutes:-

stream2chromecast.py -transcode -transcodeopts '-ss 00:15:00' myfile.mp4

cheers,

Pat

**Comment by dieuwedeboer** [comment]
Thanks Pat, worked like a charm.

I hadn't used transcode before, but it took 5x as long to load on the Chromecast and I feel the quality was a little off, but I suspect those are just side-effects of the transcode. It will have to do :)

Maybe we could put a quick note about this in the README?

**Comment by appelflap** [comment]
Try putting the '-ss' parameter in front of the '-i' which does input searching in stead of output searching. It will be quicker with loading. https://trac.ffmpeg.org/wiki/Seeking

For example:
FFMPEG = 'ffmpeg -ss 300 -i "%s" -preset ultrafast -f mp4 -frag_duration 3000 -b:v 2000k -loglevel error %s -'

**Comment by Pat-Carter** [comment]
I've added an additional parameter -transcodeinputopts. This is essentially the same as -transcodeopts but is applied to the input rather than the output of the transcoder command.

So, to seek the transcode input to 15 minutes from the start:-

stream2chromecast.py -transcodeinputopts '-ss 00:15:00' -transcode <file>

cheers,

Pat
